spring:
  application:
    name: "Helpdeskchat"
    datasource:
      url: jdbc:mysql://localhost:3306/helpDesk?useSSL=false&serverTimezone=UTC
      username: root
      password: abhi@18
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-parameter

