package com.helpdeskchatbot.helpdeskchat.tools;

import com.helpdeskchatbot.helpdeskchat.entity.Ticket;
import com.helpdeskchatbot.helpdeskchat.service.TicketService;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Component;

@Component
@Slf4j
public class ticketTools {
    private final TicketService ticketService;

    private Logger logger = LoggerFactory.getLogger(ticketTools.class);
    public ticketTools(TicketService ticketService) {
        this.ticketService = ticketService;
    }

    @Tool(description = "Create a new support ticket" +
            "IMPORTANT:\n" +
            "- Never provide ticketId\n" +
            "- ticketId is auto generated by database\n")
    public Ticket createTicketTools(
            @ToolParam(description = "Ticket details")
            Ticket ticket) {

        log.info("AI requested ticket creation");

        return ticketService.ticketCreate(ticket);
    }

    @Tool(description = "Get ticket by username")
    public Ticket getTicketByUSerName(
            @ToolParam(description = "username")
            String username) {

        return ticketService.getTicketByUsername(username);
    }

    @Tool(description = "Update existing ticket")
    public Ticket updateTicket(
            @ToolParam(description = "Updated ticket details")
            Ticket ticket) {

        return ticketService.ticketUpdate(ticket);
    }

    @Tool(description = "Get current system time")
    public String getCurrentTime() {

        return java.time.LocalDateTime.now().toString();
    }

    @Tool(description = "Get ticket by email")
    public Ticket getTicketByEmail(
            @ToolParam(description = "email")
            String email) {

        return ticketService.getTicketByEmail(email);
    }

    @Tool(description = "Delete ticket by ticket id")
    public String deleteTicketById(
            @ToolParam(description = "ticket id")
            Long ticketId) {

        ticketService.deleteTicket(ticketId);

        return "Ticket deleted successfully";
    }

    @Tool(description = "Get ticket by ticket id")
    public Ticket getTicketByTicketId(
            @ToolParam(description = "ticket id")
            Long ticketId) {

        return ticketService.getTicketByTicketId(ticketId);
    }
}
